- name: Download Espanso Debian package
  ansible.builtin.get_url:
    url: 'https://github.com/espanso/espanso/releases/latest/download/espanso-debian-{{ setup_espanso_session }}-amd64.deb'
    dest: /tmp/test-setup-ansible-espanso.deb
    mode: '0644'
  when: ansible_facts['architecture'] == 'x86_64'
- name: Install Espanso Debian package
  ansible.builtin.apt:
    deb: /tmp/test-setup-ansible-espanso.deb
  become: true
  when: ansible_facts['architecture'] == 'x86_64'
