- name: Ensure paru
  ansible.builtin.include_role:
    name: aur
- name: Install Brave from AUR
  ansible.builtin.include_role:
    name: aur
    tasks_from: install
  vars:
    aur_package: brave-bin
